# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LeeDongHeon
email: pine1578@naver.com
description:  LeeDongHeon(이동헌)<br></br>telephone: 010-3600-1578<br></br>address: 한빛관 302호(Intelligence Software lab)
baseurl:  # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ispine

# Build settings
markdown: kramdown
baseurl:
