# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LeeDongHeon
email: pine1578@naver.com
description: LeeDongHeon(이동헌)<br>telephone:&nbsp010-3600-1578<br>address:&nbsp한빛관&nbsp302호(Intelligence&nbspSoftware lab)
baseurl:  # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ispine

# Build settings
markdown: kramdown
baseurl:
